# Generated by Django 4.2 on 2024-06-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Аватарка",
                null=True,
                upload_to="image/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_nick",
            field=models.CharField(
                blank=True,
                help_text="Укажите ник телеграмма",
                max_length=200,
                null=True,
                verbose_name="Телеграмм",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ver_code",
            field=models.CharField(
                blank=True,
                help_text="Код верификации",
                max_length=4,
                null=True,
                verbose_name="Код верификации",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Укажите электронную почту",
                max_length=254,
                unique=True,
                verbose_name="Элктронная почта",
            ),
        ),
    ]
