# Generated by Django 4.2 on 2024-06-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_remove_user_username_user_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_nick",
            field=models.CharField(
                blank=True,
                help_text="Укажите id телеграмма",
                max_length=200,
                null=True,
                verbose_name="Телеграмм",
            ),
        ),
    ]
