# Generated by Django 4.2 on 2024-06-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_alter_habit_options_habit_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="Начало выполнения",
                null=True,
                verbose_name="Время",
            ),
        ),
    ]
